USE [Teste]

IF OBJECT_ID('dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI
    IF OBJECT_ID('dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE P_CFOP_VALOR_TOTAL_ICMS_IPI
(
    @pIdNotaFiscal int,
	)
AS
BEGIN
	SELECT Cfop,
	   SUM(BaseIcms) AS ValorTotalBaseICMS,
	   SUM(ValorIcms) AS ValorTotalICMS,
	   SUM(BaseIPI) AS ValorTotalBaseIPI,
	   SUM(ValorIPI) AS ValorTotalIPI
	FROM NotaFiscalItem
   WHERE IdNotaFiscal = @pIdNotaFiscal
   GROUP BY Cfop  
END
GO
GRANT EXECUTE ON dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI TO [public]
go
IF OBJECT_ID('dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_CFOP_VALOR_TOTAL_ICMS_IPI >>>'
go